function [fitresult, gof] = createFit(HP_data_res, HP_data_rmse)
%CREATEFIT(HP_DATA_RES,HP_DATA_RMSE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : HP_data_res
%      Y Output: HP_data_rmse
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Jul-2015 12:51:25


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( HP_data_res, HP_data_rmse );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [9.95840006186526e-006 -0.0299593286513421];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'HP_data_rmse vs. HP_data_res', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'HP_data_res' );
ylabel( 'HP_data_rmse' );
grid on


